### ISSUE TITLE
Create meta model in DatoCMS

### ISSUE THREAD

**Issue by iamkevinwolf** [reactcostarica/covid-19-cr#3]
Create a **singleton** model in DatoCMS for the site metadata, it should contain the following fields according to `types/content.ts`

```ts
export type Meta = {
  title: string
  description: string
  url: string
  image: string
}
```

**Comment by credondocr** [comment]
on it

**Comment by credondocr** [comment]
The model is called `siteinfo` because Datocms has some weird behaviors with the `meta` model name.
Anyways is Done

**Comment by matjack1** [comment]
hey @credondocr and @iamkevinwolf I'm part of the DatoCMS team :)

If you need any help on this feel free to ping me, I would be very happy to help you out on any blocker from our side.

About the `Meta` model, it's because `meta` is a reserved word. To avoid any issue with model naming I would recommend you to postfix every model with `_model`. Maybe not the prettiest but rock solid :P

Cheers!

**Comment by iamkevinwolf** [comment]
Hi, @matjack1! Wow thank you for your help. When I created this issue, I didn't have a clue about SEO props. So at the end, I'd create a `page` model with info about the current page, (this is for general pages that don't correspond to a model, I.e. the home page, or a list page), adding the fields `name` (identifier), `title` and `description`.

Now I just query the page with this:

```graphql
query fetchPage($name: String!) {
  page(filter: {name: {eq: $name}}) {
    seo: _seoMetaTags {
      attributes
      content
      tag
    }
  }
}
```

What do you think about that approach? May I be missing something?

**Comment by matjack1** [comment]
That's fine!

You can maybe use a `slug` field so that you have the unicity check if you want.

And then if you want to customise the SEO content you can add a SEO field in the page and add some custom SEO for each page, but I guess you've noticed that already :)

**Comment by matjack1** [comment]
Also you can have "singleton models" for pages that are different, like the home page maybe.

**Comment by iamkevinwolf** [comment]
> That's fine!
> 
> You can maybe use a `slug` field so that you have the unicity check if you want.
> 
> And then if you want to customise the SEO content you can add a SEO field in the page and add some custom SEO for each page, but I guess you've noticed that already :)

Yes, actually, I'd chose the `name` field because:

1. The home page won't have a slug, so that will be an inconsistency haha
2. Because the `id` is reserved



> Also you can have "singleton models" for pages that are different, like the home page maybe.

Yep, actually that was my idea at first, but the SEO feature blew my mind <3

**Comment by iamkevinwolf** [comment]
Hey @matjack1, I'm wondering if there is a way to reach you, I have some questions wrt DatoCMS.

**Comment by matjack1** [comment]
feel free to write me at https://www.datocms.com/support/ @iamkevinwolf  :)
