### ISSUE TITLE
Get siteInfo from DatoCMS

### ISSUE THREAD

**Issue by iamkevinwolf** [reactcostarica/covid-19-cr#8]
Get siteData from DatoCMS model instead of `src/content/meta.ts`

Steps:
1. Rename `Meta` to `SiteInfo` in `src/types/content.ts`
2. Export a `fetchSiteInfo` function that returns a `Promise<SiteInfo>` in `src/lib/datocms.ts` **above** `fetchCases`
3.  Call `fetchSiteInfo` in `getStaticProps` of `src/pages/index.tsx` and assign it to a variable `siteInfo` instead of `meta`
4. Change `meta` to `siteInfo` in `HomePageProps`
5. Remove `src/content/meta.ts`

**Comment by credondocr** [comment]
on it!
